#Nicht nötig, aber so einfach geht das:
server:
  port: 9000

# per default sind nur health und info an
management:
  endpoints:
    web:
      exposure:
        include: '*'

# h2-web-console anschalten
spring:
  h2:
    console:
      enabled: true
  #  Auto configured von spring-boot
  datasource:
    url: 'jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE' # 'jdbc:h2:file:/data/demo;DB_CLOSE_ON_EXIT=FALSE'
    driverClassName: org.h2.Driver
    username: sa
    password:

